from typing import List, Dict, Any
from langchain_core.tools import tool
import json

@tool
def report_generator_tool(candidates_data: str) -> str:
    """
    Produces a professional recruiter summary report from a list of candidate evaluation results.
    Input 'candidates_data' should be a JSON string representing a list of candidate dictionaries.
    """
    try:
        candidates = json.loads(candidates_data)
    except Exception as e:
        return f"Error parsing candidates data: {str(e)}"

    total = len(candidates)
    shortlisted = [c for c in candidates if c.get("status") == "shortlisted"]
    rejected = [c for c in candidates if c.get("status") == "rejected"]
    
    # Calculate average score
    avg_score = sum(c.get('score', 0) for c in candidates) / total if total > 0 else 0
    
    report = f"# 📋 Recruitment Selection Report\n\n"
    report += f"## 📊 Executive Summary\n"
    report += f"- **Total Candidates Evaluated:** {total}\n"
    report += f"- **Shortlisted for Interview:** {len(shortlisted)}\n"
    report += f"- **Rejection Count:** {len(rejected)}\n"
    report += f"- **Overall Pipeline Quality (Avg Score):** {avg_score:.1f}/100\n\n"
    
    report += "## 🌟 Top Talent (Shortlisted)\n"
    if not shortlisted:
        report += "No candidates met the selection threshold.\n\n"
    else:
        for i, c in enumerate(sorted(shortlisted, key=lambda x: x.get('score', 0), reverse=True), 1):
            report += f"### {i}. {c.get('name')} — Score: **{c.get('score')}**\n"
            report += f"- **Experience:** {c.get('experience')} years\n"
            report += f"- **Core Skills:** {', '.join(c.get('skills', []))}\n"
            report += f"- **AI Assessment:** {c.get('resume_summary')}\n"
            if c.get("zoom_link"):
                report += f"- **Interview Link:** [Join meeting]({c.get('zoom_link')})\n"
            report += "\n"
        
    if rejected:
        report += "## 📁 Pipeline Overview (Rejected)\n"
        report += "| Candidate Name | Score | Key Reason |\n"
        report += "| :--- | :--- | :--- |\n"
        for c in sorted(rejected, key=lambda x: x.get('score', 0), reverse=True):
            reason = "Score below threshold"
            report += f"| {c.get('name')} | {c.get('score')} | {reason} |\n"
        report += "\n"
        
    report += "---\n"
    report += "*Generated by AI Recruitment Agent*"
    
    return report
